const root=document.querySelector('[data-option]');
const option=Number(root.dataset.option); const started=performance.now();
const specs={
1:{name:'Native MP4',format:'H.264 MP4',asset:'assets/animation.mp4'},
2:{name:'Animated APNG',format:'APNG',asset:'assets/animation.apng'},
3:{name:'Animated WebP',format:'Animated WebP',asset:'assets/animation.webp'},
4:{name:'CSS sprite strips',format:'5 static WebP strips',asset:'assets/strips/strip-1.webp'},
5:{name:'Canvas sprite animation',format:'5 static WebP strips',asset:'assets/strips/strip-1.webp'},
6:{name:'Canvas predecoded frames',format:'150 predecoded frames from 5 WebP strips',asset:'assets/strips/strip-1.webp'}
}[option];
const stage=document.querySelector('.stage'); let firstVisible=null, firstAnimated=null, measuredFps='estimated 30';
const markVisible=()=>{if(firstVisible===null)firstVisible=performance.now()-started; stage.classList.add('ready');};
const markAnimated=()=>{if(firstAnimated===null)firstAnimated=performance.now()-started; renderHUD();};
const loadImage=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src});
async function assetBytes(paths){const vals=await Promise.all(paths.map(async p=>{const r=await fetch(p,{cache:'force-cache'});return Number(r.headers.get('content-length'))||0}));return vals.reduce((a,b)=>a+b,0)}
let bytes=0;
function renderHUD(){document.querySelector('[data-hud]').innerHTML=`<dl><dt>Implementation</dt><dd>${specs.name}</dd><dt>Asset format</dt><dd>${specs.format}</dd><dt>Asset dimensions</dt><dd>${option>=4?'5 × 9000×300 strips'+(option===6?'; 150 × 300×300 decoded frames':''):'300×300'}</dd><dt>Asset file size</dt><dd>${bytes?formatBytes(bytes):'measuring…'}</dd><dt>Source frames</dt><dd>150</dd><dt>First visible frame</dt><dd>${firstVisible===null?'waiting…':Math.round(firstVisible)+' ms'}</dd><dt>First animated frame</dt><dd>${firstAnimated===null?'waiting…':Math.round(firstAnimated)+' ms'}</dd><dt>Animation FPS</dt><dd>${measuredFps}</dd></dl>`}
function formatBytes(n){return n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB'}
async function native(){const el=option===1?document.createElement('video'):document.createElement('img');if(option===1){el.autoplay=true;el.muted=true;el.loop=true;el.playsInline=true;el.addEventListener('loadeddata',markVisible,{once:true});if(el.requestVideoFrameCallback){let c=0,t0;const cb=(now)=>{c++;if(c===1)t0=now;if(c===2)markAnimated();if(now-t0<1000)el.requestVideoFrameCallback(cb);else{measuredFps=(c*1000/(now-t0)).toFixed(1)+' measured';renderHUD()}};el.requestVideoFrameCallback(cb)}else el.addEventListener('playing',()=>requestAnimationFrame(markAnimated),{once:true})}else{el.onload=()=>{markVisible();setTimeout(markAnimated,34)}}el.src=specs.asset;stage.append(el)}
async function strips(canvasMode=false){const paths=Array.from({length:5},(_,i)=>`assets/strips/strip-${i+1}.webp`);const imgs=await Promise.all(paths.map(loadImage));if(!canvasMode){imgs.forEach((_,i)=>{const d=document.createElement('div');d.className='sprite-layer';d.style.backgroundImage=`url(${paths[i]})`;stage.append(d)});const layers=[...stage.querySelectorAll('.sprite-layer')];let last=-1,zero=performance.now();function tick(now){const f=Math.floor((now-zero)/1000)%5;if(f!==last){if(last>=0)layers[last].classList.remove('active');layers[f].classList.add('active');last=f}requestAnimationFrame(tick)}markVisible();setTimeout(markAnimated,34);requestAnimationFrame(tick)}else{const c=document.createElement('canvas');c.width=c.height=300;stage.append(c);const x=c.getContext('2d');let zero=performance.now(),last=-1,count=0,windowStart=zero;function tick(now){const frame=Math.floor((now-zero)/1000*30)%150;if(frame!==last){x.drawImage(imgs[Math.floor(frame/30)],(frame%30)*300,0,300,300,0,0,300,300);last=frame;count++;if(firstVisible===null)markVisible();else if(firstAnimated===null)markAnimated()}if(now-windowStart>=1000){measuredFps=(count*1000/(now-windowStart)).toFixed(1)+' measured';count=0;windowStart=now;renderHUD()}requestAnimationFrame(tick)}requestAnimationFrame(tick)}}
async function decoded(){const paths=Array.from({length:5},(_,i)=>`assets/strips/strip-${i+1}.webp`);const strips=await Promise.all(paths.map(loadImage));let frames=[];if('createImageBitmap'in window){for(let f=0;f<150;f++)frames.push(await createImageBitmap(strips[Math.floor(f/30)],(f%30)*300,0,300,300));specs.format='150 cropped ImageBitmaps from 5 WebP strips'}else{for(let f=0;f<150;f++){const frame=document.createElement('canvas');frame.width=frame.height=300;frame.getContext('2d').drawImage(strips[Math.floor(f/30)],(f%30)*300,0,300,300,0,0,300,300);frames.push(frame)}specs.format='150 pre-rendered canvases from 5 WebP strips'}const c=document.createElement('canvas');c.width=c.height=300;stage.append(c);const x=c.getContext('2d');let zero=performance.now(),last=-1,count=0,windowStart=zero;function tick(now){const f=Math.floor((now-zero)/1000*30)%150;if(f!==last){x.drawImage(frames[f],0,0,300,300);last=f;count++;if(firstVisible===null)markVisible();else if(firstAnimated===null)markAnimated()}if(now-windowStart>=1000){measuredFps=(count*1000/(now-windowStart)).toFixed(1)+' measured';count=0;windowStart=now;renderHUD()}requestAnimationFrame(tick)}requestAnimationFrame(tick)}
async function boot(){renderHUD();try{if(option<=3){bytes=await assetBytes([specs.asset]);renderHUD();native()}else{const p=Array.from({length:5},(_,i)=>`assets/strips/strip-${i+1}.webp`);bytes=await assetBytes(p);renderHUD();if(option<=5)await strips(option===5);else await decoded()}}catch(e){document.querySelector('.loading').textContent='Asset failed to load';console.error(e)}}boot();
